// Generated by jextract

package com.microsoft.win32;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

import java.lang.foreign.*;
import java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang=c :
 * struct _SECURITY_ATTRIBUTES {
 *     DWORD nLength;
 *     LPVOID lpSecurityDescriptor;
 *     BOOL bInheritHandle;
 * }
 * }
 */
public class _SECURITY_ATTRIBUTES {
	public static _SECURITY_ATTRIBUTES allocate(SegmentAllocator allocator) {
		MemorySegment ms = allocator.allocate(LAYOUT);
		setNLength(ms, getSizeof());

		return new _SECURITY_ATTRIBUTES(ms);
	}

	public static _SECURITY_ATTRIBUTES of(SegmentAllocator allocator,
			MemorySegment securityDescriptorSegment) {
		_SECURITY_ATTRIBUTES result = allocate(allocator);
		result.setSecurityDescriptor(securityDescriptorSegment);
		return result;
	}

	private final MemorySegment segment;

	public _SECURITY_ATTRIBUTES(MemorySegment segment) {
		this.segment = segment;
	}

	public int getLength() {
		return getNLength(segment);
	}

	public MemorySegment getSecurityDescriptor() {
		return getLpSecurityDescriptor(segment);
	}

	public void setSecurityDescriptor(MemorySegment sd) {
		setLpSecurityDescriptor(segment, sd);
	}

	public boolean isInheritHandle() {
		return getBInheritHandle(segment) != 0;
	}

	public void setInheritHandle(boolean b) {
		setBInheritHandle(segment, b ? 1 : 0);
	}

	public MemorySegment getMemorySegment() {
		return segment;
	}

	private static final GroupLayout LAYOUT = MemoryLayout.structLayout(
		win32_sddl_h.C_LONG.withName("nLength"),
		MemoryLayout.paddingLayout(4),
		win32_sddl_h.C_POINTER.withName("lpSecurityDescriptor"),
		win32_sddl_h.C_INT.withName("bInheritHandle"),
		MemoryLayout.paddingLayout(4)).withName("_SECURITY_ATTRIBUTES");

	private static final OfInt nLength_LAYOUT = (OfInt) LAYOUT.select(groupElement("nLength"));
	private static final long nLength_OFFSET = LAYOUT.byteOffset(groupElement("nLength"));

	public static int getNLength(MemorySegment struct) {
		return struct.get(nLength_LAYOUT, nLength_OFFSET);
	}

	public static void setNLength(MemorySegment struct, int fieldValue) {
		struct.set(nLength_LAYOUT, nLength_OFFSET, fieldValue);
	}

	private static final AddressLayout lpSecurityDescriptor_LAYOUT =
		(AddressLayout) LAYOUT.select(groupElement("lpSecurityDescriptor"));

	private static final long lpSecurityDescriptor_OFFSET =
		LAYOUT.byteOffset(groupElement("lpSecurityDescriptor"));

	public static MemorySegment getLpSecurityDescriptor(MemorySegment struct) {
		return struct.get(lpSecurityDescriptor_LAYOUT, lpSecurityDescriptor_OFFSET);
	}

	public static void setLpSecurityDescriptor(MemorySegment struct, MemorySegment fieldValue) {
		struct.set(lpSecurityDescriptor_LAYOUT, lpSecurityDescriptor_OFFSET, fieldValue);
	}

	private static final OfInt bInheritHandle_LAYOUT =
		(OfInt) LAYOUT.select(groupElement("bInheritHandle"));

	private static final long bInheritHandle_OFFSET =
		LAYOUT.byteOffset(groupElement("bInheritHandle"));

	public static int getBInheritHandle(MemorySegment struct) {
		return struct.get(bInheritHandle_LAYOUT, bInheritHandle_OFFSET);
	}

	public static void setBInheritHandle(MemorySegment struct, int fieldValue) {
		struct.set(bInheritHandle_LAYOUT, bInheritHandle_OFFSET, fieldValue);
	}

	public static int getSizeof() {
		return (int) LAYOUT.byteSize();
	}
}
