/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by jextract

package com.microsoft.win32;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

import ghidra.pty.windows.Win32Err;

public class win32_sddl_h extends win32_sddl_h$shared {

    win32_sddl_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("Advapi32"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());


    private static class ConvertStringSecurityDescriptorToSecurityDescriptorW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            win32_sddl_h.C_INT,
            win32_sddl_h.C_POINTER,
            win32_sddl_h.C_LONG,
            win32_sddl_h.C_POINTER,
            win32_sddl_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ConvertStringSecurityDescriptorToSecurityDescriptorW");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC, Win32Err.OPT_CAPTURE_LASTERROR);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * BOOL ConvertStringSecurityDescriptorToSecurityDescriptorW(LPCWSTR StringSecurityDescriptor, DWORD StringSDRevision, PSECURITY_DESCRIPTOR *SecurityDescriptor, PULONG SecurityDescriptorSize)
     * }
     */
    public static FunctionDescriptor ConvertStringSecurityDescriptorToSecurityDescriptorW$descriptor() {
        return ConvertStringSecurityDescriptorToSecurityDescriptorW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * BOOL ConvertStringSecurityDescriptorToSecurityDescriptorW(LPCWSTR StringSecurityDescriptor, DWORD StringSDRevision, PSECURITY_DESCRIPTOR *SecurityDescriptor, PULONG SecurityDescriptorSize)
     * }
     */
    public static MethodHandle ConvertStringSecurityDescriptorToSecurityDescriptorW$handle() {
        return ConvertStringSecurityDescriptorToSecurityDescriptorW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * BOOL ConvertStringSecurityDescriptorToSecurityDescriptorW(LPCWSTR StringSecurityDescriptor, DWORD StringSDRevision, PSECURITY_DESCRIPTOR *SecurityDescriptor, PULONG SecurityDescriptorSize)
     * }
     */
    public static MemorySegment ConvertStringSecurityDescriptorToSecurityDescriptorW$address() {
        return ConvertStringSecurityDescriptorToSecurityDescriptorW.ADDR;
    }

    /**
     * {@snippet lang=c :
     * BOOL ConvertStringSecurityDescriptorToSecurityDescriptorW(LPCWSTR StringSecurityDescriptor, DWORD StringSDRevision, PSECURITY_DESCRIPTOR *SecurityDescriptor, PULONG SecurityDescriptorSize)
     * }
     */
    public static int ConvertStringSecurityDescriptorToSecurityDescriptorW(MemorySegment cs, MemorySegment StringSecurityDescriptor, int StringSDRevision, MemorySegment SecurityDescriptor, MemorySegment SecurityDescriptorSize) {
        var mh$ = ConvertStringSecurityDescriptorToSecurityDescriptorW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ConvertStringSecurityDescriptorToSecurityDescriptorW", StringSecurityDescriptor, StringSDRevision, SecurityDescriptor, SecurityDescriptorSize);
            }
            return (int)mh$.invokeExact(cs, StringSecurityDescriptor, StringSDRevision, SecurityDescriptor, SecurityDescriptorSize);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

	private static final int SECURITY_DESCRIPTOR_REVISION = (int) 1L;

	/**
	 * {@snippet lang=c :
	 * #define SECURITY_DESCRIPTOR_REVISION 1
	 * }
	 */
	public static int SECURITY_DESCRIPTOR_REVISION() {
		return SECURITY_DESCRIPTOR_REVISION;
	}

}

