/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by jextract

package org.unix;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

import ghidra.pty.unix.UnixErr;

public class stat_h extends stat_h$shared {

    stat_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class mkfifo {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            stat_h.C_INT,
            stat_h.C_POINTER,
            stat_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mkfifo");

		public static final MethodHandle HANDLE =
			Linker.nativeLinker().downcallHandle(ADDR, DESC, UnixErr.OPT_CAPTURE_ERRNO);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int mkfifo(const char *__path, __mode_t __mode)
     * }
     */
    public static FunctionDescriptor mkfifo$descriptor() {
        return mkfifo.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int mkfifo(const char *__path, __mode_t __mode)
     * }
     */
    public static MethodHandle mkfifo$handle() {
        return mkfifo.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int mkfifo(const char *__path, __mode_t __mode)
     * }
     */
    public static MemorySegment mkfifo$address() {
        return mkfifo.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int mkfifo(const char *__path, __mode_t __mode)
     * }
     */
	public static int mkfifo(MemorySegment cs, MemorySegment __path, int __mode) {
        var mh$ = mkfifo.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mkfifo", __path, __mode);
            }
			return (int) mh$.invokeExact(cs, __path, __mode);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

